import os

Import('env')

_INCLUDES = [Dir('../include').abspath]

_SOURCES = ['Warp.cpp', 'WarpBilinear.cpp',
	'WarpPerspective.cpp', 'WarpPerspectiveBilinear.cpp']
_SOURCES = [File('../src/' + s).abspath for s in _SOURCES]

env.Append(APP_SOURCES = _SOURCES)
env.Append(CPPPATH = _INCLUDES)

Return('env')
